export const countries = [
  'Alemania',
  'Argelia',
  'Argentina',
  'Arabia Saudí',
  'Australia',
  'Austria',
  'Bélgica',
  'Bosnia y Herzegovina',
  'Brasil',
  'Cabo Verde',
  'Canadá',
  'Catar',
  'Colombia',
  'Costa de Marfil',
  'Croacia',
  'Curazao',
  'Ecuador',
  'Egipto',
  'Escocia',
  'España',
  'Estados Unidos',
  'Francia',
  'Ghana',
  'Haití',
  'Inglaterra',
  'Irak',
  'Irán',
  'Japón',
  'Jordania',
  'Marruecos',
  'México',
  'Noruega',
  'Nueva Zelanda',
  'Países Bajos',
  'Panamá',
  'Paraguay',
  'Portugal',
  'RD Congo',
  'República Checa',
  'República de Corea',
  'Senegal',
  'Sudáfrica',
  'Suecia',
  'Suiza',
  'Túnez',
  'Turquía',
  'Uruguay',
  'Uzbekistán'
]