export const countries = [
  'México',
  'Sudáfrica',
  'República de Corea',
  'República Checa',
  'Canadá',
  'Bosnia y Herzegovina',
  'Estados Unidos',
  'Paraguay',
  'Catar',
  'Suiza',
  'Brasil',
  'Marruecos',
  'Haití',
  'Escocia',
  'Australia',
  'Turquía',
  'Alemania',
  'Curazao',
  'Países Bajos',
  'Japón',
  'Costa de Marfil',
  'Ecuador',
  'Suecia',
  'Túnez',
  'España',
  'Cabo Verde',
  'Bélgica',
  'Egipto',
  'Arabia Saudí',
  'Uruguay',
  'Irán',
  'Nueva Zelanda',
  'Francia',
  'Senegal',
  'Irak',
  'Noruega',
  'Argentina',
  'Argelia',
  'Austria',
  'Jordania',
  'Portugal',
  'RD Congo',
  'Inglaterra',
  'Croacia',
  'Ghana',
  'Panamá',
  'Colombia',
  'Uzbekistán'
]